FROM node:18

WORKDIR /app

COPY . /app

RUN apt-get update && apt-get install -y python3 python3-pip

RUN pip3 install --no-cache-dir -r server/requirements.txt

WORKDIR /app/frontend
RUN npm install

RUN npm run build

WORKDIR /app

EXPOSE 3000

CMD ["sh", "-c", "cd server && uvicorn main:app --host 0.0.0.0 --port 8000 & cd ../frontend && npm start"]